<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="../../styles/styleGeneral.css">
    <link rel="stylesheet" href="style.css">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="script.js"></script>
    <title>Ejercicio 5</title>
</head>
<body>
      
      <main>
        <header class="container-fluid" id="header">
          <div ><h1>Ejercicio 5</h1> <a href="../../index.html"><button class="btn btn-primary">Volver</button></a></div>
          
          <p>Se solicita al usuario que introduzca un valor. Si el valor es superior a 10, inferior a 5, o no es un número,
            vamos a lanzar un error. El error es entonces atrapado por el argumento de la captura y dependiendo del
            error generado se presentará el mensaje de error apropiado.</p>

            <button onclick="errorCheck()" class="width100 btn btn-primary">Control de errores try_catch_throw</button>
        </header>
      
      


          
          
      </main>
      
      
          <script src="/docs/5.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  
        </body>
      </html>